[workspace]
name = "light_pollution_map"

members = [
    "sat_dl",
    "garstang",
    # "map_generation"
]

[profile.dev]
debug = true
opt-level = 1

[profile.release]
debug = true
opt-level = 1

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ardijan Rexhaj"]
