[workspace]
members = [
    "sat_dl",
    "garstang",
    "map_generation"
]

[workspace.package]
name = "light_pollution_map"
version = "0.1.0"
edition = "2021"
authors = ["Ardijan Rexhaj"]

# [dependencies]