[package]
name = "garstang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sequential-integration = "1.0.2"
image = "0.24.6"