FROM docker.io/fedora:37

RUN dnf update -y

RUN dnf install python-devel -y pip gdal gdal-devel gdal-python-tools python-wheel


RUN pip install numpy gdal

WORKDIR /geotiff_converter

COPY . .

CMD python3 hdf5_to_geotiff.py