FROM docker.io/fedora:37 AS stage0

RUN dnf update -y

RUN dnf install -y rust cargo gdal gdal-devel hdf5 hdf5-devel pkg-config openssl-devel

WORKDIR /downloader

COPY ./Cargo.toml ./Cargo.toml
COPY ./dummy ./src

RUN cargo build
RUN cargo build --release

COPY ./src ./src

CMD cargo run

